version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kuafor_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: kuafor_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kuafor_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: kuafor_app
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    environment:
      DB_HOST: db
    ports:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    user: "1000:1000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: appointment-hairstyler-system-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

# sudo certbot --nginx -d erencelik.info -d admin.erencelik.info -d api.erencelik.info -d www.erencelik.info --register-unsafely-without-email
volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge